name: "Count commits ahead of the main"

on:
  workflow_dispatch:
#  pull_request:
#    branches: [main]

jobs:
  commits_ahead_of_main:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    
    - name: "Add current branch to env"
      run: |
        set -o xtrace
        git fetch
        echo "CURRENT_BRANCH="${GITHUB_REF##*/}"" >> $GITHUB_ENV

    - name: "Add commits number ahead of the main to env"
      run: |
        set -o xtrace
        echo "COMMITS_AHEAD_MAIN="$(git rev-list ${{ env.CURRENT_BRANCH }}.."origin main" --count)"" >> $GITHUB_ENV
        echo "C_A_M="$(git rev-list --left-right ${{ env.CURRENT_BRANCH }}..."origin main")"" >> $GITHUB_ENV
        
    - name: "Output information"
      run: |
        set -o xtrace
        echo "Commits number ["${{ env.CURRENT_BRANCH }}"] is ahead of the [origin main]: ${{ env.COMMITS_AHEAD_MAIN }}"
  
