name: "Count commits ahead of the main"

on:
  workflow_dispatch:
#  pull_request:
#    branches: [main]

jobs:
  commits_ahead_of_main:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: "Add commits number ahead of the main to env"
      run: |
        set -o xtrace
        echo COMMITS_AHEAD_MAIN=$(git rev-list --left-only --count ${GITHUB_REF_NAME}...origin/main) >> $GITHUB_ENV
        
    - name: "Output information"
      run: |
        set -o xtrace
        echo "The ${GITHUB_REF_NAME} is ahead of the [origin/main] by ${{ env.COMMITS_AHEAD_MAIN }} commits"
        
    - name: "Fails if the ${GITHUB_REF_NAME} is ahead of the [origin/main] by more than 40 commits"
      if: ${{ env.COMMITS_AHEAD_MAIN }} > 40
      run: |
        echo "${{ env.COMMITS_AHEAD_MAIN }} > 40"
        set -o xtrace
        exit 1
