# This is a basic workflow to help you get started with Actions

name: Build Site

on: 
  push:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:    
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
          node-version: '14'
          
    - name: Install dependencies
      run:
        npm install
        npm install -g yarn
        npm install -g gatsby-cli
          
    - name: Build Site
      run:
        npm run build
