name: Publish

on: 
  workflow_dispatch:
    inputs:
        version-postfix:
          type: choice
          description: "It adds alpha or beta postfix to version."
          required: false
          options: 
          - alpha
          - beta

jobs:
    publish_utbot_java:
      runs-on: ubuntu-20.04

      steps:
      - uses: actions/github-script@v1
        env:
          type_of_release: ${{ steps.step-id.outputs.output-version-postfix }}
        with:
          script:
            console.log(process.env.type_of_release)
          
      - uses: actions/checkout@v2
          
      - name: Set environment variables
        run: |
          echo "VERSION="$(date +%Y).$(date +%-m)"" >> $GITHUB_ENV
          
          
      - name: Get version
        run: |
          echo ${{ env.VERSION }}
