name: Publish

on: workflow_dispatch
  
jobs:
    publish_utbot_java:
      runs-on: ubuntu-20.04
      
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'liberica'
          java-package: jdk+fx
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.8
          
      - name: Set environment variables
        run: |
          echo "YEAR=$(date +%Y)" >> $GITHUB_ENV
          echo "MONTH=$(date +%m)" >> $GITHUB_ENV
          echo "VERSION=${{ env.YEAR }}.${{ env.MONTH }}" >> $GITHUB_ENV
          
      - name: Get version
        run: echo ${{ env.VERSION }}
