name: Publish

on: 
  workflow_dispatch:
    inputs:
        version-postfix:
          type: choice
          description: "It adds alpha or beta postfix to version."
          required: true
          default: no-postfix
          options:
          - no-postfix
          - alpha
          - beta

jobs:
    publish_utbot_java:
      runs-on: ubuntu-20.04

      steps:          
      - uses: actions/checkout@v2
          
      - name: Set environment variable
        run:
          echo "VERSION="$(date +%Y).$(date +%-m)"" >> $GITHUB_ENV
      
      - name: Print version
        run:
          echo ${{ env.VERSION }}
