name: Publish

on: workflow_dispatch
  
jobs:
    publish_utbot_java:
      runs-on: ubuntu-20.04
      
      steps:
          
      - name: Set environment variables
        run: |
          echo "YEAR=$(date +%Y)" >> $GITHUB_ENV
          echo "MONTH=$(date +%m)" >> $GITHUB_ENV
          echo "VERSION=${{ env.YEAR }}.${{ env.MONTH }}" >> $GITHUB_ENV
          
      - name: Get version
        run: echo ${{ env.VERSION }}
