name: Publish

on: 
  workflow_dispatch:
    inputs:
        name:
          description: "It adds postfix to version. E.g. version is 2022.5, postfix is alpha. Result version: 2022.5-alpha"
          required: false
          options: 
          - alpha
          - beta

jobs:
    publish_utbot_java:
      runs-on: ubuntu-20.04

      steps:
      - uses: actions/github-script@v1
        env:
          type_of_release: ${{ steps.step-id.outputs.output-name }}
        with:
          script:
            console.log(process.env.type_of_release)
          
      - uses: actions/checkout@v2
          
      - name: Set environment variables
        run: |
          echo "VERSION="$(date +%Y).$(date +%-m)"" >> $GITHUB_ENV
          
          
      - name: Get version
        run: |
          echo ${{ env.VERSION }}
