name: Publish

on: workflow_dispatch
  
jobs:
    publish_utbot_java:
      runs-on: ubuntu-20.04
      
      steps:
      - uses: actions/checkout@v2
          
      - name: Set environment variables
        run: |
          echo "TEST_VAR=5" >> $GITHUB_ENV
          echo "YEAR=$(date +%Y)" >> $GITHUB_ENV
          echo "MONTH=$(date +%m)" >> $GITHUB_ENV
          echo "VERSION=${{ env.YEAR }}.${{ env.MONTH }}" >> $GITHUB_ENV
          
      - name: Get version
        run: |
          echo ${{ env.VERSION }}
          echo ${{ env.TEST_VAR }}
          echo ${{ env.YEAR }}
          echo ${{ env.MONTH }}
