name: Publish

on: 
  workflow_dispatch:
    inputs:
        version-postfix:
          type: choice
          description: "It adds alpha or beta postfix to version."
          required: true
          default: no-postfix
          options:
          - no-postfix
          - alpha
          - beta

jobs:
    publish_utbot_java:
      runs-on: ubuntu-20.04

      steps:          
      - uses: actions/checkout@v2
          
      - name: Set environment variables
        run: |
          echo "VERSION="$(date +%Y).$(date +%-m)"" >> $GITHUB_ENV
          echo "POSTFIX=${{ github.event.inputs.version-postfix }}" >> $GITHUB_ENV
      
      - name: Print envs
        run: |
          echo ${{ env.VERSION }}
          echo ${{ env.POSTFIX }}
          
      - name: Create version with postfix 'alpha'
        if: ${{ (env.POSTFIX == 'alpha') || (env.POSTFIX == 'beta') }}
        run: |
          echo "Alpha or beta"
          echo ${{ env.POSTFIX }}
          
      - name: Create version with postfix 'beta'
        if: ${{ env.POSTFIX == 'beta' }}
        run: |
          echo "Alpha or beta"
          echo ${{ env.POSTFIX }}
